// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ein.proto

package ein

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LastQuote struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Time                 int64    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastQuote) Reset()         { *m = LastQuote{} }
func (m *LastQuote) String() string { return proto.CompactTextString(m) }
func (*LastQuote) ProtoMessage()    {}
func (*LastQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{0}
}

func (m *LastQuote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastQuote.Unmarshal(m, b)
}
func (m *LastQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastQuote.Marshal(b, m, deterministic)
}
func (m *LastQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastQuote.Merge(m, src)
}
func (m *LastQuote) XXX_Size() int {
	return xxx_messageInfo_LastQuote.Size(m)
}
func (m *LastQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_LastQuote.DiscardUnknown(m)
}

var xxx_messageInfo_LastQuote proto.InternalMessageInfo

func (m *LastQuote) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LastQuote) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *LastQuote) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *LastQuote) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type UpdateInfo struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UpdateNum            int64    `protobuf:"varint,2,opt,name=updateNum,proto3" json:"updateNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfo) Reset()         { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()    {}
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{1}
}

func (m *UpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfo.Unmarshal(m, b)
}
func (m *UpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfo.Marshal(b, m, deterministic)
}
func (m *UpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfo.Merge(m, src)
}
func (m *UpdateInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateInfo.Size(m)
}
func (m *UpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfo proto.InternalMessageInfo

func (m *UpdateInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UpdateInfo) GetUpdateNum() int64 {
	if m != nil {
		return m.UpdateNum
	}
	return 0
}

type QuoteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteRequest) Reset()         { *m = QuoteRequest{} }
func (m *QuoteRequest) String() string { return proto.CompactTextString(m) }
func (*QuoteRequest) ProtoMessage()    {}
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{2}
}

func (m *QuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteRequest.Unmarshal(m, b)
}
func (m *QuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteRequest.Marshal(b, m, deterministic)
}
func (m *QuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteRequest.Merge(m, src)
}
func (m *QuoteRequest) XXX_Size() int {
	return xxx_messageInfo_QuoteRequest.Size(m)
}
func (m *QuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteRequest proto.InternalMessageInfo

func (m *QuoteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StreamRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{3}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LastQuotesResponse struct {
	Data                 []*LastQuote `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LastQuotesResponse) Reset()         { *m = LastQuotesResponse{} }
func (m *LastQuotesResponse) String() string { return proto.CompactTextString(m) }
func (*LastQuotesResponse) ProtoMessage()    {}
func (*LastQuotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{4}
}

func (m *LastQuotesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastQuotesResponse.Unmarshal(m, b)
}
func (m *LastQuotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastQuotesResponse.Marshal(b, m, deterministic)
}
func (m *LastQuotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastQuotesResponse.Merge(m, src)
}
func (m *LastQuotesResponse) XXX_Size() int {
	return xxx_messageInfo_LastQuotesResponse.Size(m)
}
func (m *LastQuotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastQuotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastQuotesResponse proto.InternalMessageInfo

func (m *LastQuotesResponse) GetData() []*LastQuote {
	if m != nil {
		return m.Data
	}
	return nil
}

type LastQuoteResponse struct {
	Data                 *LastQuote `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LastQuoteResponse) Reset()         { *m = LastQuoteResponse{} }
func (m *LastQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*LastQuoteResponse) ProtoMessage()    {}
func (*LastQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9005a3b1336ea6b, []int{5}
}

func (m *LastQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastQuoteResponse.Unmarshal(m, b)
}
func (m *LastQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastQuoteResponse.Marshal(b, m, deterministic)
}
func (m *LastQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastQuoteResponse.Merge(m, src)
}
func (m *LastQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_LastQuoteResponse.Size(m)
}
func (m *LastQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastQuoteResponse proto.InternalMessageInfo

func (m *LastQuoteResponse) GetData() *LastQuote {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LastQuote)(nil), "ein.LastQuote")
	proto.RegisterType((*UpdateInfo)(nil), "ein.UpdateInfo")
	proto.RegisterType((*QuoteRequest)(nil), "ein.QuoteRequest")
	proto.RegisterType((*StreamRequest)(nil), "ein.StreamRequest")
	proto.RegisterType((*LastQuotesResponse)(nil), "ein.LastQuotesResponse")
	proto.RegisterType((*LastQuoteResponse)(nil), "ein.LastQuoteResponse")
}

func init() { proto.RegisterFile("ein.proto", fileDescriptor_d9005a3b1336ea6b) }

var fileDescriptor_d9005a3b1336ea6b = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0x02, 0x31,
	0x10, 0x85, 0xa9, 0x05, 0x92, 0x1d, 0x51, 0xa1, 0x31, 0xb0, 0x12, 0x0f, 0x6b, 0x4f, 0x7b, 0x02,
	0x83, 0x07, 0x4d, 0xbc, 0xa8, 0x89, 0x41, 0x13, 0x63, 0x62, 0x8d, 0x07, 0xb9, 0x15, 0x18, 0xa1,
	0x91, 0x6d, 0x57, 0xda, 0x3d, 0xe0, 0xbf, 0xf3, 0x9f, 0x99, 0x2d, 0x86, 0x05, 0x95, 0xdb, 0xf4,
	0xeb, 0x7b, 0xcd, 0x9b, 0x99, 0x42, 0x80, 0x4a, 0x77, 0xd2, 0xb9, 0x71, 0x86, 0x51, 0x54, 0x9a,
	0x4b, 0x08, 0x1e, 0xa4, 0x75, 0x4f, 0x99, 0x71, 0xc8, 0x9a, 0x50, 0xb5, 0x8b, 0x64, 0x68, 0x66,
	0xe1, 0x4e, 0x44, 0xe2, 0x40, 0xfc, 0x9c, 0xd8, 0x21, 0x54, 0xd2, 0xb9, 0x1a, 0x61, 0x48, 0x23,
	0x12, 0x13, 0xb1, 0x3c, 0x30, 0x06, 0x65, 0xab, 0x3e, 0x31, 0xac, 0x44, 0x24, 0xa6, 0xc2, 0xd7,
	0x39, 0x73, 0x2a, 0xc1, 0xb0, 0xba, 0x64, 0x79, 0xcd, 0xef, 0x00, 0x5e, 0xd2, 0xb1, 0x74, 0x78,
	0xaf, 0xdf, 0x0c, 0x3b, 0x86, 0x20, 0xa7, 0xd6, 0xc9, 0x24, 0x0d, 0x89, 0x97, 0x15, 0x20, 0xbf,
	0xcd, 0xbc, 0xf6, 0x31, 0x4b, 0x7c, 0x08, 0x2a, 0x0a, 0xc0, 0x23, 0xa8, 0xf9, 0xa0, 0x02, 0x3f,
	0x32, 0xb4, 0x8e, 0xd5, 0x81, 0xbe, 0xe3, 0xc2, 0xbf, 0x12, 0x88, 0xbc, 0xe4, 0x27, 0xb0, 0xf7,
	0xec, 0xe6, 0x28, 0x93, 0xed, 0x92, 0x0b, 0x60, 0xab, 0x8e, 0xad, 0x40, 0x9b, 0x1a, 0x6d, 0x91,
	0x71, 0x28, 0x8f, 0xa5, 0x93, 0x21, 0x89, 0x68, 0xbc, 0xdb, 0xdb, 0xef, 0xe4, 0x63, 0x5a, 0xc9,
	0x84, 0xbf, 0xe3, 0xe7, 0xd0, 0x28, 0xd0, 0x5f, 0x23, 0xd9, 0x66, 0xec, 0x7d, 0x11, 0xa0, 0xb7,
	0x4a, 0xb3, 0x2b, 0xa8, 0xf7, 0xd1, 0x5d, 0xcf, 0x66, 0x45, 0x00, 0xd6, 0xf0, 0x8e, 0xf5, 0xb6,
	0xda, 0xad, 0xcd, 0x47, 0x56, 0x21, 0x79, 0x89, 0x5d, 0x42, 0xad, 0x8f, 0xae, 0xd8, 0xd8, 0x3f,
	0xee, 0xe6, 0xaf, 0x08, 0xeb, 0xe6, 0xfa, 0x72, 0x38, 0x6b, 0xeb, 0x60, 0x5e, 0xbd, 0x31, 0xb3,
	0xf6, 0x81, 0x67, 0x85, 0x88, 0x97, 0x4e, 0xc9, 0xcd, 0xd1, 0xa0, 0x35, 0x51, 0x6e, 0x9a, 0x0d,
	0x3b, 0x23, 0x93, 0x74, 0x07, 0x53, 0xa9, 0x27, 0xaf, 0xe8, 0xba, 0xa8, 0xf4, 0xb0, 0xea, 0xff,
	0xd3, 0xd9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xd8, 0x06, 0x8c, 0x5c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EinClient is the client API for Ein service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EinClient interface {
	GetAllLastQuotes(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*LastQuotesResponse, error)
	GetLastQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*LastQuoteResponse, error)
	StreamUpdateInfo(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Ein_StreamUpdateInfoClient, error)
}

type einClient struct {
	cc *grpc.ClientConn
}

func NewEinClient(cc *grpc.ClientConn) EinClient {
	return &einClient{cc}
}

func (c *einClient) GetAllLastQuotes(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*LastQuotesResponse, error) {
	out := new(LastQuotesResponse)
	err := c.cc.Invoke(ctx, "/ein.Ein/GetAllLastQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *einClient) GetLastQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*LastQuoteResponse, error) {
	out := new(LastQuoteResponse)
	err := c.cc.Invoke(ctx, "/ein.Ein/GetLastQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *einClient) StreamUpdateInfo(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Ein_StreamUpdateInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ein_serviceDesc.Streams[0], "/ein.Ein/StreamUpdateInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &einStreamUpdateInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ein_StreamUpdateInfoClient interface {
	Recv() (*UpdateInfo, error)
	grpc.ClientStream
}

type einStreamUpdateInfoClient struct {
	grpc.ClientStream
}

func (x *einStreamUpdateInfoClient) Recv() (*UpdateInfo, error) {
	m := new(UpdateInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EinServer is the server API for Ein service.
type EinServer interface {
	GetAllLastQuotes(context.Context, *QuoteRequest) (*LastQuotesResponse, error)
	GetLastQuote(context.Context, *QuoteRequest) (*LastQuoteResponse, error)
	StreamUpdateInfo(*StreamRequest, Ein_StreamUpdateInfoServer) error
}

func RegisterEinServer(s *grpc.Server, srv EinServer) {
	s.RegisterService(&_Ein_serviceDesc, srv)
}

func _Ein_GetAllLastQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EinServer).GetAllLastQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ein.Ein/GetAllLastQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EinServer).GetAllLastQuotes(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ein_GetLastQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EinServer).GetLastQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ein.Ein/GetLastQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EinServer).GetLastQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ein_StreamUpdateInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EinServer).StreamUpdateInfo(m, &einStreamUpdateInfoServer{stream})
}

type Ein_StreamUpdateInfoServer interface {
	Send(*UpdateInfo) error
	grpc.ServerStream
}

type einStreamUpdateInfoServer struct {
	grpc.ServerStream
}

func (x *einStreamUpdateInfoServer) Send(m *UpdateInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _Ein_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ein.Ein",
	HandlerType: (*EinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllLastQuotes",
			Handler:    _Ein_GetAllLastQuotes_Handler,
		},
		{
			MethodName: "GetLastQuote",
			Handler:    _Ein_GetLastQuote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdateInfo",
			Handler:       _Ein_StreamUpdateInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ein.proto",
}
